apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ma14nahm5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ma14nahm5-java-quarkus-gitops